### ISSUE TITLE
Bug while fetching repositories using Issue.find_all(user, repo)

### ISSUE THREAD

**Issue by fcoury** [fcoury/octopi#11]
require File.join(File.dirname(**FILE**), '..', 'lib', 'octopi')

include Octopi

user = user.find("bcalloway")

It seems that when issue is called using your find method, there is the following error: ./lib/../lib/octopi.rb:139:in find_plural': undefined methodeach' for nil:NilClass (NoMethodError)

```
from ./lib/../lib/octopi.rb:133:in `find_all'
from ./lib/../lib/octopi.rb:237:in `find_all'
from lib/myissues.rb:17
```

This is the code that produces the error:

```
require File.join(File.dirname(FILE), '..', 'lib', 'octopi')
include Octopi

user = User.find("bcalloway")
puts user.name

repo = user.repository("myproject")
puts repo.description

issue = Issue.find_all(user.login, repo.name)
puts "First open issue: #{issue.number} - #{issue.title} - Created at: #{issue.created_at}"
```

**Comment by fcoury** [comment]
Added alternate syntax for fetching Issues and Commits: find_all(user, repo), with no hashes. Closed by 113ceee07f8d94fe6c82c5ad147084420f879615.
