### ISSUE TITLE
Handling of HTTP Errors

### ISSUE THREAD

**Issue by runpaint** [fcoury/octopi#20]
I got the following stack trace when running the examples. It's presumably due to my ISP's transparent proxy being flaky, thus implying a bug in Net::HTTP's handling of a pretty common condition, but in any case we should probably handle these type of cases. We can probably deal with this when my [Document Status Codes and Their Implications](http://github.com/develop/develop.github.com/issues#issue/15) issue has been resolved. This would constitute a retryable error, I suspect.

```
/usr/lib/ruby/1.8/net/http.rb:2022:in `read_status_line': wrong status line: "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"" (Net::HTTPBadResponse)
  from /usr/lib/ruby/1.8/net/http.rb:2009:in `read_new'
  from /usr/lib/ruby/1.8/net/http.rb:1050:in `request'
  from /usr/lib/ruby/1.8/net/http.rb:1037:in `request'
  from /usr/lib/ruby/1.8/net/http.rb:543:in `start'
  from /usr/lib/ruby/1.8/net/http.rb:1035:in `request'
  from /var/lib/gems/1.8/gems/httparty-0.4.2/lib/httparty/request.rb:69:in `perform_actual_request'
  from /var/lib/gems/1.8/gems/httparty-0.4.2/lib/httparty/request.rb:73:in `get_response'
  from /var/lib/gems/1.8/gems/httparty-0.4.2/lib/httparty/request.rb:40:in `perform'
  from /var/lib/gems/1.8/gems/httparty-0.4.2/lib/httparty.rb:156:in `perform_request'
  from /var/lib/gems/1.8/gems/httparty-0.4.2/lib/httparty.rb:122:in `get'
  from ./examples/../lib/octopi.rb:172:in `get'
  from ./examples/../lib/octopi.rb:155:in `submit'
  from ./examples/../lib/octopi.rb:171:in `get'
  from ./examples/../lib/octopi.rb:113:in `find'
  from ./examples/../lib/octopi/resource.rb:34:in `find'
  from ./examples/../lib/octopi/repository.rb:37:in `find'
  from ./examples/../lib/octopi/user.rb:24:in `repository'
  from examples/overall.rb:25
```

**Comment by radar** [comment]
Is this still an issue?
