### ISSUE TITLE
Error listing issues for a project

### ISSUE THREAD

**Issue by icco** [fcoury/octopi#40]
I just installed octopi and I'm getting the following error. Anyone know why?

/var/lib/gems/1.8/gems/octopi-0.2.2/lib/octopi/commit.rb:2: uninitialized constant Octopi::Base (NameError)
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /var/lib/gems/1.8/gems/octopi-0.2.2/lib/octopi.rb:15
    from /var/lib/gems/1.8/gems/octopi-0.2.2/lib/octopi.rb:15:in `each'
    from /var/lib/gems/1.8/gems/octopi-0.2.2/lib/octopi.rb:15
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from ./erasmus/github.rb:4
    from ./bots.rb:7:in`require'
    from ./bots.rb:7

The code that is using this is at http://github.com/icco/erasmus/blob/master/lib/erasmus/github.rb

**Comment by icco** [comment]
Aparrently this is supposed to be used with 1.9 not 1.8, which might be where my problem lies...

**Comment by xiongchiamiov** [comment]
Working off of (essentially) [the same code](http://github.com/xiongchiamiov/erasmus/blob/master/lib/bots.rb), I get (basically) the same error on a fresh install of ruby- and rubygems-1.8:

<pre>
> ruby-1.8 bots.rb                                
/opt/ruby1.8/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- mechanize (LoadError)
        from /opt/ruby1.8/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from /opt/ruby1.8/lib/ruby/gems/1.8/gems/octopi-0.2.2/lib/octopi.rb:4
        from /opt/ruby1.8/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from /opt/ruby1.8/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from ./erasmus/github.rb:4
        from bots.rb:7:in `require'
        from bots.rb:7
</pre>

So my guess is that octopi isn't 1.8 compatible.

**Comment by radar** [comment]
It's neither. Did you install the mechanize gem?

**Comment by radar** [comment]
Could you please try installing the latest from gemcutter too (which should automatically install mechanize too)

**Comment by icco** [comment]
I just did sudo gem install octopi, if it's not one of the dependencies for the gem, then I didn't.
