### ISSUE TITLE
Bug in Ruby 1.9.2

### ISSUE THREAD

**Issue by stevenheidel** [fcoury/octopi#49]
The same code runs fine in Ruby 1.8.7, but in 1.9.2 I get:

```
/home/steven/.rvm/gems/ruby-1.9.2-p0/gems/octopi-0.2.8/lib/octopi/api.rb:198:in `submit': undefined method `first' for "application/x-yaml; charset=utf-8":String (NoMethodError)
from /home/steven/.rvm/gems/ruby-1.9.2-p0/gems/octopi-0.2.8/lib/octopi/api.rb:118:in `get'
from /home/steven/.rvm/gems/ruby-1.9.2-p0/gems/octopi-0.2.8/lib/octopi/api.rb:100:in `find'
from /home/steven/.rvm/gems/ruby-1.9.2-p0/gems/octopi-0.2.8/lib/octopi/resource.rb:41:in `find'
from /home/steven/.rvm/gems/ruby-1.9.2-p0/gems/octopi-0.2.8/lib/octopi/repository.rb:82:in `find'
```

</code>

**Comment by wilkerlucio** [comment]
have same problem here

**Comment by radar** [comment]
I think this is fixed with the latest version. Please try that.

**Comment by stevenheidel** [comment]
Works for me!

**Comment by radar** [comment]
Thanks for confirming.
