### ISSUE TITLE
Syntax Error when loading YAML from Github

### ISSUE THREAD

**Issue by printinghappy** [fcoury/octopi#72]
I'm running octopi 0.4.5 and recently I've started seeing a parse error when pulling data from Github, it looks like. Has anything changed on the Github side?

Here's my code:

authenticated do
  <my code, but never gets here>
end

Here's my stack trace:

ArgumentError in PagesController#commits

syntax error on line 2, col 41: `  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# githubog: http://ogp.me/ns/fb/githubog#">'
Rails.root: /Users/badgeville/git/widgets

Application Trace | Framework Trace | Full Trace
/Users/badgeville/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/yaml.rb:133:in `load'
/Users/badgeville/.rvm/rubies/ruby-1.8.7-p174/lib/ruby/1.8/yaml.rb:133:in`load'
httparty (0.8.2) lib/httparty/parser.rb:120:in `yaml'
httparty (0.8.2) lib/httparty/parser.rb:136:in`send'
httparty (0.8.2) lib/httparty/parser.rb:136:in `parse_supported_format'
httparty (0.8.2) lib/httparty/parser.rb:103:in`parse'
httparty (0.8.2) lib/httparty/parser.rb:66:in `call'
httparty (0.8.2) lib/httparty/request.rb:238:in`parse_response'
httparty (0.8.2) lib/httparty/request.rb:208:in `handle_response'
httparty (0.8.2) lib/httparty/request.rb:88:in`perform'
httparty (0.8.2) lib/httparty.rb:395:in `perform_request'
httparty (0.8.2) lib/httparty.rb:347:in`get'
octopi (0.4.5) lib/octopi/api.rb:118:in `get'
octopi (0.4.5) lib/octopi/api.rb:182:in`submit'
octopi (0.4.5) lib/octopi/api.rb:117:in `get'
octopi (0.4.5) lib/octopi/api.rb:100:in`find'
octopi (0.4.5) lib/octopi/resource.rb:41:in `find'

**Comment by francois2metz** [comment]
The API v2 is now deprecated.

**Comment by printinghappy** [comment]
Thanks, "octokit" works well.
